version: 2
dist: releases
snapshot:
  version_template: '{{ trimprefix .Summary "v" }}'

builds:
  - id: default
    binary: gptscript-credential-sqlite-v{{ .Version }}-{{ .Os }}-{{ .Arch }}
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X "github.com/gptscript-ai/gptscript/pkg/version.Tag=v{{ .Version }}"

archives:
  # Disable archives, we just want the binaries
  - id: no_archives
    format: binary
    builds:
      - build_all

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge pull request"

release:
  github:
    owner: g-linville
    name: gptscript-credential-sqlite
  prerelease: auto
