version: 2
dist: releases
snapshot:
  version_template: '{{ trimprefix .Summary "v" }}'

builds:
  - id: default
    binary: gptscript-credential-sqlite
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

archives:
  # Disable archives, we just want the binaries
  - id: no_archives
    format: binary
    name_template: "gptscript-credential-sqlite-{{ .Os }}-{{ .Arch }}"
    builds:
      - default

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge pull request"

release:
  github:
    owner: gptscript-ai
    name: gptscript-credential-sqlite
  prerelease: auto
